apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: sample-ace-project
  namespace: cp4i
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-AMYG-BQ2E4U
    use: CloudPakForIntegrationProduction
  pod:
    containers:
      runtime:
        image: "us.icr.io/cp4i-gse-poc/sample-ace-project:6670498e46fa1a0b9536aa97317ef21324f301aa"
    imagePullSecrets:
      - name: ibm-cr-pull-secret
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 11.0.0
  configurations: ["odbc-conf"]
